import {assetUrl} from './asset-url';
import React,{useEffect,useRef,useState,Suspense,lazy} from 'react';
import {rooms} from './data';
import {ATRIUM_ID} from './building-layout';
import {CINEMA_ID} from './cinema-layout';
import ExhibitionPlan from './ExhibitionPlan';
import {useCaseMotion} from './use-case-motion';
import {useCaseScroll} from './use-case-scroll';
import './case-study.css';
function LogoUnavailable(){return <div><p>입체 로고를 불러오지 못했어요.</p><button className="case-text" onClick={()=>location.reload()}>새로고침</button></div>;}
// A visitor may still have the previous bundle open during a deployment.
// A removed lazy chunk must not take the whole case-study page down.
const LogoStudy=lazy(()=>import('./LogoStudy').catch(()=>({default:LogoUnavailable})));
const chapters=['개요','과제와 목표','콘셉트와 아이덴티티','디자인 시스템','경험 흐름과 화면','인터랙션과 검증'];
const shot=id=>assetUrl(`/process/room-${String(id+1).padStart(2,'0')}.png?v=spatial-furnishing-v8`);
export default function Introduction({onClose,onEnter,onGo,ready,failed,sound}){
 const ref=useRef(null),[active,setActive]=useState(0),[selected,setSelected]=useState(0);
 const smooth=useCaseScroll(ref);
 useCaseMotion(ref);
 useEffect(()=>{const before=document.activeElement,el=ref.current;el.querySelector('button')?.focus({preventScroll:true});const key=e=>{if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'){const items=[...el.querySelectorAll('button,a,input,[tabindex="0"]')].filter(item=>!item.disabled),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};el.addEventListener('keydown',key);return()=>{el.removeEventListener('keydown',key);before?.focus({preventScroll:true});};},[]);
 useEffect(()=>{const el=ref.current;let frame;const update=()=>{frame=null;const edge=el.getBoundingClientRect().top+120;let chapter=0;el.querySelectorAll('[data-chapter]').forEach(section=>{if(section.getBoundingClientRect().top<=edge)chapter=Number(section.dataset.chapter);});setActive(chapter);};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};el.addEventListener('scroll',scroll,{passive:true});update();return()=>{el.removeEventListener('scroll',scroll);cancelAnimationFrame(frame);};},[]);
 const jump=index=>{setActive(index);const root=ref.current,target=root.querySelector(`[data-chapter="${index}"]`),top=root.scrollTop+target.getBoundingClientRect().top-root.getBoundingClientRect().top-root.querySelector('.case-index').offsetHeight-12;if(smooth.current)smooth.current.scrollTo(top,{duration:1.1});else root.scrollTo({top,behavior:'instant'});};
 const title=(n,label,text)=><div className="case-heading"><span>{String(n+1).padStart(2,'0')} / {label}</span><h2>{text}</h2></div>;
 return <section ref={ref} className="introduction case-study" role="dialog" aria-modal="true" aria-label="전시 소개">
  <div className="case-top"><span>AFTERIMAGE</span><button onClick={onClose}>전시로 돌아가기</button></div>
  <nav className="case-index" aria-label="전시 제작 과정">{chapters.map((name,i)=><button key={name} onClick={()=>jump(i)} aria-current={active===i?'step':undefined}>{String(i+1).padStart(2,'0')} {name}</button>)}</nav>
  <div className="case-content">
   <section className="case-cover" data-chapter="0"><h1>AFTERIMAGE</h1><div className="case-tagline"><b>잔상</b><p>눈을 감은 뒤에도 남는 열 개의 장면.</p></div><img className="case-wide" src={assetUrl('/process/atrium.png?v=lobby-fountain-v11')} alt="중앙의 흐르는 분수와 긴 천창, 목재 루버와 벤치, 식재와 안내 가구가 있는 실제 채광 홀" fetchPriority="high"/><div className="case-metadata"><span>3D WEB EXHIBITION</span><span>2026</span><span>기획 · 브랜딩 · 디자인 · 개발</span><button className="case-outline" disabled={!ready||failed} onClick={onEnter}>전시 입장</button></div><h2>웹을 읽는 대신, 공간을 걷다.</h2><p className="case-lead">채광 홀과 두 개의 전시 동, 열 개의 방과 스무 점의 작품, 2층의 상영관. 화면을 넘기는 대신 직접 걷고, 시선을 돌리고, 작품을 다른 각도에서 감상하는 디지털 전시입니다.</p></section>
   <section className="case-section" data-chapter="1">{title(1,'BRIEF','작품만큼, 관람의 경험도.')}<div className="case-two"><p className="case-lead">감상의 깊이는 공간에서,<br/>경험의 밀도는 반응에서.</p><p>AFTERIMAGE는 가상의 디지털 아트와 입체 조형을 위한 웹 전시입니다. 관람자가 작품을 더 가까이, 다른 각도에서 보고 싶어지는 순간에 집중했습니다. 이동과 시선, 회전과 소리가 하나의 관람 흐름으로 이어지도록 설계했습니다.</p></div><div className="case-decisions">{[['평범한 탐색','직접 걷고 둘러보는 공간','W A S D와 모바일 조이스틱, 드래그 시선, 점프'],['수동적인 감상','내가 선택하는 작품의 각도','실제 3D 조각의 회전, 회화 확대'],['단절된 조작','입력과 움직임 사이의 여유','드래그 후 감속, 회전의 부드러운 시작과 정지'],['반복되는 장식','작품을 위한 담백한 인터페이스','프리텐다드, 직접적인 버튼 이름, 최소한의 선']].map(([before,after,how])=><div key={before}><span>{before}</span><b>{after}</b><p>{how}</p></div>)}</div><small className="case-note">설계 기준: 풍부한 반응, 작품과 연결된 아이덴티티, 누구나 이해할 수 있는 조작.</small></section>
   <section className="case-section" data-chapter="2">{title(2,'IDENTITY','겹쳐진 문, 남겨진 형태.')}<div className="case-two"><p className="case-lead">본 장면과 남은 장면 사이.<br/>두 개의 어긋난 문틀.</p><p>잔상을 겹친 프레임으로 표현했습니다. 화면의 마크, 워드마크와 공간의 입체 사인은 같은 형태를 공유합니다. 이미지와 3D 파일을 따로 내려받아 다른 매체에서도 사용할 수 있습니다.</p></div><div className="case-identity"><div><img src={assetUrl('/logo.svg')} alt="두 개의 어긋난 문틀과 AFTERIMAGE 워드마크"/><span>VECTOR / SVG</span></div><div className="case-logo-study"><Suspense fallback={<p>입체 로고 준비 중</p>}><LogoStudy/></Suspense><span>3D / 천천히 회전 · 드래그하여 감상</span></div></div><div className="case-downloads"><a href={assetUrl('/logo.svg')} download>SVG 로고 저장</a><a href={assetUrl('/logo.glb')} download>3D 로고 저장</a></div><div className="case-concept-pair"><img src={shot(0)} alt="실제로 구현된 두 문틀 조각" loading="lazy"/><p>다음 장면을 떠올리는 입구.<br/>로고와 조각을 하나의 공간 언어로 연결했습니다.</p></div></section>
   <section className="case-section" data-chapter="3">{title(3,'DESIGN SYSTEM','공간은 풍부하게, 화면은 차분하게.')}<div className="case-palette">{[['#181A19','Charcoal'],['#ECE5D8','Ivory / 벽'],['#D9D3C8','Limestone / 바닥'],['#C3A379','Bronze / 작품'],['#426393','Blue / 작품']].map(([hex,label])=><div key={hex}><i style={{background:hex}}/><span>{label}</span><small>{hex}</small></div>)}</div><div className="case-type"><div><span>TYPOGRAPHY</span><h3>Pretendard</h3><p>작품 설명과 조작 안내를 명확하게 전달하는 글꼴.</p></div><div><p style={{fontWeight:900}}>잔상 AFTERIMAGE <small>Black / 900</small></p><p style={{fontWeight:700}}>열 개의 장면 <small>Bold / 700</small></p><p>서두르지 않고, 원하는 방향으로. <small>Regular / 400</small></p></div></div><div className="case-component-study"><span>COMPONENTS IN USE</span><button className="entry" disabled={!ready||failed} onClick={onEnter}>전시 입장</button><button className="case-outline" disabled={!ready||failed} onClick={()=>onGo(selected)}>선택한 방 관람</button><button className="case-text" onClick={sound.toggle} aria-pressed={sound.enabled}>{sound.enabled?'소리 끄기':'소리 켜기'}</button></div></section>
   <section className="case-section" data-chapter="4">{title(4,'EXPERIENCE','하나의 입구, 여러 방식의 관람.')}<ol className="case-flow"><li><span>01</span>전시 입장</li><li><span>02</span>걷기 · 둘러보기</li><li><span>03</span>작품 선택</li><li><span>04</span>조각 회전 · 회화 확대</li></ol><p className="case-flow-note">높은 천장의 채광 홀에서 01–05와 06–10 전시 동으로 이어집니다. 방의 크기와 높이를 달리하고, 꺾이는 복도를 지나 홀로 돌아오는 두 순환 동선으로 설계했습니다. 홀에는 물이 흐르는 석재 분수와 목재 루버, 벤치, 식재와 안내 가구를 두어 머무는 공간을 만들었습니다. 전시실에는 식재와 러그, 독서용 테이블과 조명, 도자기와 도록을 놓은 콘솔을 배치했습니다. 복도의 부조와 선반, 화분과 휴식 벤치가 방 사이의 경험을 이어줍니다. 홀의 계단실과 지붕이 있는 연결 통로를 지나면 2층 상영관으로 이어집니다. 벤치와 의자에서는 앉아 공간과 작품을 감상할 수 있습니다. 전시 지도에서는 원하는 방이나 작품, 상영관으로 바로 이동할 수 있습니다.</p><div className="case-room-preview"><div><ExhibitionPlan className="case-plan" selected={selected} onSelect={setSelected}/><div className="case-room-tabs" aria-label="미리 볼 전시실">{rooms.map(r=><button key={r.id} aria-pressed={selected===r.id} onClick={()=>setSelected(r.id)}>{r.number}<span>{r.title}</span></button>)}</div></div><figure><img key={selected} src={shot(selected)} alt={`${rooms[selected].number} ${rooms[selected].title} 실제 렌더링`} loading="lazy"/><figcaption><div><span>{rooms[selected].number} / {String(rooms.length).padStart(2,'0')}</span><h3>{rooms[selected].title}</h3><small>{rooms[selected].en}</small></div><button className="case-outline" disabled={!ready||failed} onClick={()=>onGo(selected)}>이 방 관람</button></figcaption></figure></div><figure className="case-cinema"><img className="case-wide" src={assetUrl('/process/cinema.png?v=cinema-seating-v7')} alt="월넛 흡음 벽과 계단식 좌석이 있는 실제 2층 상영관, 입체 금속 리본 영상이 보이는 대형 스크린" loading="lazy"/><figcaption><div><span>2F / SCREENING HALL</span><h3>마지막 장면은, 앉아서.</h3><p>문을 지나 입체 리본이 펼쳐지고, 빛의 입자로 여운을 남기는 세 장면의 48초 영상 ‘여운의 문’. 부드러운 음악과 함께 반복 상영합니다. 좌석에 실제로 앉아 낮아진 시점에서 감상합니다. 영상과 음악은 이 전시를 위해 제작했습니다.</p></div><button className="case-outline" disabled={!ready||failed} onClick={()=>onGo(CINEMA_ID)}>상영관 입장</button></figcaption></figure></section>
   <section className="case-section" data-chapter="5">{title(5,'INTERACTION','움직임이 남기는 감각.')}<div className="case-interaction-screens"><figure><img src={assetUrl('/process/desktop-inspector.png?v=cinema-seating-v7')} alt="실제 데스크톱 조각 감상 화면" loading="lazy"/><figcaption><b>01 — 작품을 드래그하고 회전하기</b><p>시선과 작품 회전에 감속을 적용했습니다. 시선 초기화와 회전 정지는 항상 직접 선택할 수 있습니다.</p></figcaption></figure><figure><img src={assetUrl('/process/mobile-walk.png?v=spatial-furnishing-v8')} alt="모바일 화면의 이동 패드와 3D 전시" loading="lazy"/><figcaption><b>02 — 두 손으로 공간을 둘러보기</b><p>왼쪽은 조이스틱 이동, 끝까지 밀면 달리기. 오른쪽은 시선과 점프. 작은 화면에서도 작품 선택과 전시 지도를 함께 제공합니다.</p></figcaption></figure></div><div className="case-sound-study"><div><h3>03 — 방마다 다른 여운</h3><p>전시를 위해 만든 따뜻한 피아노 선율과 또렷한 발소리. 로비 분수에 다가가면 물소리가 부드럽게 커집니다.<br/>첫 조작부터 시작하며, 언제든 끄거나 음량을 조절할 수 있습니다. 상영관에서는 전시 배경음을 낮추고 영상의 음악을 들려줍니다.</p></div><button className="case-outline" onClick={sound.toggle} aria-pressed={sound.enabled}>{sound.enabled?'소리 끄기':'소리 켜기'}</button><label htmlFor="case-volume">음량 <output>{Math.round(sound.volume*100)}%</output><input id="case-volume" type="range" min="0" max="1" step=".01" value={sound.volume} onChange={e=>sound.changeVolume(Number(e.target.value))}/></label>{sound.error&&<p role="status">{sound.error}</p>}</div><div className="case-validation"><span>IMPLEMENTATION REVIEW</span><p>데스크톱·태블릿·모바일 크기에서 방 이동, 계단으로 2층 오르내리기, 드래그와 회전, 회화 확대, 벤치·의자 앉기와 일어나기, 영상 재생·탐색과 소리 조절을 점검했습니다. 작은 화면의 가로 넘침과 입장 위치의 이동 문제를 수정하고, 움직임 감소 설정에서도 관람 기능을 사용할 수 있도록 했습니다.</p><p className="case-note">현재 주름의 조형 디테일과 공간의 조명에는 최초 시안과 차이가 남아 있습니다. 이 프로젝트의 시안은 제작 방향을 보여주는 이미지이며, 실제 전시 화면과 구분됩니다.</p></div></section>
   <div className="case-end"><p>열 개의 방, 당신의 속도로.<small>작품과 작가는 가상입니다. 회화·시안은 AI로 제작했으며, 공간·조각·상호작용과 상영 영상·음악은 코드로 구현했습니다.</small></p><button className="entry" disabled={!ready||failed} onClick={()=>onGo(ATRIUM_ID)}>처음부터 관람</button></div>
  </div>
 </section>;
}

