import React,{useEffect,useRef,useState,Suspense,lazy} from 'react';
import {rooms} from './data';
import {useCaseMotion} from './use-case-motion';
import './case-study.css';
const LogoStudy=lazy(()=>import('./LogoStudy'));
const chapters=['개요','과제와 목표','콘셉트와 아이덴티티','디자인 시스템','경험 흐름과 화면','인터랙션과 검증'];
const shot=id=>`/process/room-${String(id+1).padStart(2,'0')}.png`;
function Plan({selected,onSelect}){return <svg className="case-plan" viewBox="0 0 620 270" role="img" aria-label="01부터 06까지 복도로 연결된 순환형 전시"><path d="M85 72H535V198H85Z" fill="none" stroke="currentColor" strokeOpacity=".3" strokeWidth="15"/>{rooms.map(r=>{const x=85+r.x/22*225,y=72-r.z/22*126;return <g key={r.id} onClick={()=>onSelect(r.id)}><rect x={x-49} y={y-40} width="98" height="80" fill={selected===r.id?'#eeeae2':'#181a19'} stroke="#bcb9b1"/><text x={x} y={y+7} textAnchor="middle" fill={selected===r.id?'#181a19':'#eeeae2'}>{r.number}</text></g>;})}</svg>;}
export default function Introduction({onClose,onEnter,onGo,ready,failed,sound}){
 const ref=useRef(null),[active,setActive]=useState(0),[selected,setSelected]=useState(0);
 useCaseMotion(ref);
 useEffect(()=>{const before=document.activeElement,el=ref.current;el.querySelector('button')?.focus({preventScroll:true});const key=e=>{if(e.key==='Escape'){e.preventDefault();onClose();}if(e.key==='Tab'){const items=[...el.querySelectorAll('button,a,input,[tabindex="0"]')].filter(item=>!item.disabled),first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};el.addEventListener('keydown',key);return()=>{el.removeEventListener('keydown',key);before?.focus({preventScroll:true});};},[]);
 useEffect(()=>{const el=ref.current;let frame;const update=()=>{frame=null;const edge=el.getBoundingClientRect().top+120;let chapter=0;el.querySelectorAll('[data-chapter]').forEach(section=>{if(section.getBoundingClientRect().top<=edge)chapter=Number(section.dataset.chapter);});setActive(chapter);};const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};el.addEventListener('scroll',scroll,{passive:true});update();return()=>{el.removeEventListener('scroll',scroll);cancelAnimationFrame(frame);};},[]);
 const jump=index=>{setActive(index);ref.current.querySelector(`[data-chapter="${index}"]`).scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});};
 const title=(n,label,text)=><div className="case-heading"><span>{String(n+1).padStart(2,'0')} / {label}</span><h2>{text}</h2></div>;
 return <section ref={ref} className="introduction case-study" role="dialog" aria-modal="true" aria-label="전시 소개">
  <div className="case-top"><span>AFTERIMAGE</span><button onClick={onClose}>전시로 돌아가기</button></div>
  <nav className="case-index" aria-label="전시 제작 과정">{chapters.map((name,i)=><button key={name} onClick={()=>jump(i)} aria-current={active===i?'step':undefined}>{String(i+1).padStart(2,'0')} {name}</button>)}</nav>
  <div className="case-content">
   <section className="case-cover" data-chapter="0"><h1>AFTERIMAGE</h1><div className="case-tagline"><b>잔상</b><p>눈을 감은 뒤에도 남는 여섯 개의 장면.</p></div><img className="case-wide" src={shot(0)} alt="AFTERIMAGE 실제 3D 전시의 두 석회석 문틀" fetchPriority="high"/><div className="case-metadata"><span>3D WEB EXHIBITION</span><span>2026</span><span>기획 · 브랜딩 · 디자인 · 개발</span><button className="case-outline" disabled={!ready||failed} onClick={onEnter}>전시 입장</button></div><h2>웹을 읽는 대신, 공간을 걷다.</h2><p className="case-lead">여섯 개의 방과 열두 점의 작품. 화면을 넘기는 대신 직접 걷고, 시선을 돌리고, 작품을 다른 각도에서 감상하는 디지털 전시입니다.</p></section>
   <section className="case-section" data-chapter="1">{title(1,'BRIEF','작품만큼, 관람의 경험도.')}<div className="case-two"><p className="case-lead">감상의 깊이는 공간에서,<br/>경험의 밀도는 반응에서.</p><p>AFTERIMAGE는 가상의 디지털 아트와 입체 조형을 위한 웹 전시입니다. 관람자가 작품을 더 가까이, 다른 각도에서 보고 싶어지는 순간에 집중했습니다. 이동과 시선, 회전과 소리가 하나의 관람 흐름으로 이어지도록 설계했습니다.</p></div><div className="case-decisions">{[['평범한 탐색','직접 걷고 둘러보는 공간','W A S D와 모바일 이동 패드, 드래그 시선'],['수동적인 감상','내가 선택하는 작품의 각도','실제 3D 조각의 회전, 회화 확대'],['단절된 조작','입력과 움직임 사이의 여유','드래그 후 감속, 회전의 부드러운 시작과 정지'],['반복되는 장식','작품을 위한 담백한 인터페이스','프리텐다드, 직접적인 버튼 이름, 최소한의 선']].map(([before,after,how])=><div key={before}><span>{before}</span><b>{after}</b><p>{how}</p></div>)}</div><small className="case-note">설계 기준: 풍부한 반응, 작품과 연결된 아이덴티티, 누구나 이해할 수 있는 조작.</small></section>
   <section className="case-section" data-chapter="2">{title(2,'IDENTITY','겹쳐진 문, 남겨진 형태.')}<div className="case-two"><p className="case-lead">본 장면과 남은 장면 사이.<br/>두 개의 어긋난 문틀.</p><p>잔상을 겹친 프레임으로 표현했습니다. 화면의 마크, 워드마크와 공간의 입체 사인은 같은 형태를 공유합니다. 이미지와 3D 파일을 따로 내려받아 다른 매체에서도 사용할 수 있습니다.</p></div><div className="case-identity"><div><img src="/logo.svg" alt="두 개의 어긋난 문틀과 AFTERIMAGE 워드마크"/><span>VECTOR / SVG</span></div><div className="case-logo-study"><Suspense fallback={<p>입체 로고 준비 중</p>}><LogoStudy/></Suspense><span>3D / 천천히 회전 · 드래그하여 감상</span></div></div><div className="case-downloads"><a href="/logo.svg" download>SVG 로고 저장</a><a href="/logo.glb" download>3D 로고 저장</a></div><div className="case-concept-pair"><img src={shot(0)} alt="실제로 구현된 두 문틀 조각" loading="lazy"/><p>다음 장면을 떠올리는 입구.<br/>로고와 조각을 하나의 공간 언어로 연결했습니다.</p></div></section>
   <section className="case-section" data-chapter="3">{title(3,'DESIGN SYSTEM','공간은 풍부하게, 화면은 차분하게.')}<div className="case-palette">{[['#181A19','Charcoal'],['#EEEAE2','Ivory'],['#BCB9B1','Muted'],['#C3A379','Bronze / 작품'],['#426393','Blue / 작품']].map(([hex,label])=><div key={hex}><i style={{background:hex}}/><span>{label}</span><small>{hex}</small></div>)}</div><div className="case-type"><div><span>TYPOGRAPHY</span><h3>Pretendard</h3><p>작품 설명과 조작 안내를 명확하게 전달하는 글꼴.</p></div><div><p style={{fontWeight:900}}>잔상 AFTERIMAGE <small>Black / 900</small></p><p style={{fontWeight:700}}>여섯 개의 장면 <small>Bold / 700</small></p><p>서두르지 않고, 원하는 방향으로. <small>Regular / 400</small></p></div></div><div className="case-component-study"><span>COMPONENTS IN USE</span><button className="entry" disabled={!ready||failed} onClick={onEnter}>전시 입장</button><button className="case-outline" disabled={!ready||failed} onClick={()=>onGo(selected)}>선택한 방 관람</button><button className="case-text" onClick={sound.toggle} aria-pressed={sound.enabled}>{sound.enabled?'소리 끄기':'소리 켜기'}</button></div></section>
   <section className="case-section" data-chapter="4">{title(4,'EXPERIENCE','하나의 입구, 여러 방식의 관람.')}<ol className="case-flow"><li><span>01</span>전시 입장</li><li><span>02</span>걷기 · 둘러보기</li><li><span>03</span>작품 선택</li><li><span>04</span>조각 회전 · 회화 확대</li></ol><p className="case-flow-note">전시 지도는 언제든 원하는 방이나 작품으로 이동하는 또 하나의 입구입니다.</p><div className="case-room-preview"><div><Plan selected={selected} onSelect={setSelected}/><div className="case-room-tabs" aria-label="미리 볼 전시실">{rooms.map(r=><button key={r.id} aria-pressed={selected===r.id} onClick={()=>setSelected(r.id)}>{r.number}<span>{r.title}</span></button>)}</div></div><figure><img key={selected} src={shot(selected)} alt={`${rooms[selected].number} ${rooms[selected].title} 실제 렌더링`} loading="lazy"/><figcaption><div><span>{rooms[selected].number} / 06</span><h3>{rooms[selected].title}</h3><small>{rooms[selected].en}</small></div><button className="case-outline" disabled={!ready||failed} onClick={()=>onGo(selected)}>이 방 관람</button></figcaption></figure></div></section>
   <section className="case-section" data-chapter="5">{title(5,'INTERACTION','움직임이 남기는 감각.')}<div className="case-interaction-screens"><figure><img src="/process/desktop-inspector.png" alt="실제 데스크톱 조각 감상 화면" loading="lazy"/><figcaption><b>01 — 작품을 드래그하고 회전하기</b><p>시선과 작품 회전에 감속을 적용했습니다. 시선 초기화와 회전 정지는 항상 직접 선택할 수 있습니다.</p></figcaption></figure><figure><img src="/process/mobile-walk.png" alt="모바일 화면의 이동 패드와 3D 전시" loading="lazy"/><figcaption><b>02 — 두 손으로 공간을 둘러보기</b><p>왼쪽은 이동, 오른쪽은 시선. 작은 화면에서도 작품 선택과 전시 지도를 함께 제공합니다.</p></figcaption></figure></div><div className="case-sound-study"><div><h3>03 — 방마다 다른 여운</h3><p>전시를 위해 만든 앰비언트 선율과 발소리.<br/>소리는 관람자가 켤 때 시작합니다.</p></div><button className="case-outline" onClick={sound.toggle} aria-pressed={sound.enabled}>{sound.enabled?'소리 끄기':'소리 켜기'}</button><label htmlFor="case-volume">음량 <output>{Math.round(sound.volume*100)}%</output><input id="case-volume" type="range" min="0" max="1" step=".01" value={sound.volume} onChange={e=>sound.changeVolume(Number(e.target.value))}/></label>{sound.error&&<p role="status">{sound.error}</p>}</div><div className="case-validation"><span>IMPLEMENTATION REVIEW</span><p>데스크톱·태블릿·모바일 크기에서 방 이동, 드래그와 회전, 회화 확대, 소리 조절을 점검했습니다. 작은 화면의 가로 넘침과 입장 위치의 이동 문제를 수정하고, 움직임 감소 설정에서도 관람 기능을 사용할 수 있도록 했습니다.</p><p className="case-note">현재 주름의 조형 디테일과 공간의 조명에는 최초 시안과 차이가 남아 있습니다. 이 프로젝트의 시안은 제작 방향을 보여주는 이미지이며, 실제 전시 화면과 구분됩니다.</p></div></section>
   <div className="case-end"><p>여섯 개의 방, 당신의 속도로.<small>작품과 작가는 가상입니다. 회화·시안은 AI로 제작했으며, 공간·조각·상호작용은 코드로 구현했습니다.</small></p><button className="entry" disabled={!ready||failed} onClick={()=>onGo(0)}>처음부터 관람</button></div>
  </div>
 </section>;
}

